name: Deploy
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        working-directory: '.'
        run: |
          export APP_NAME=cryptogator-api
          export IMAGE_NAME=samdouble/$APP_NAME
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.ref_name }} -f Dockerfile.prod .
          docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
          docker push $IMAGE_NAME --all-tags
