name: Checks
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '8.0'
          mongodb-replica-set: rs0
      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Audit
        run: |
          npm run audit
      - name: Test
        run: |
          export MONGO_URL=mongodb://127.0.0.1:27017/app
          npm run test-ci
      - name: Build
        run: |
          npm run build
